In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
sns.set()

In [2]:
df=pd.read_csv("root_cause_analysis.csv")

In [3]:
df

ID  CPU_LOAD  MEMORY_LEAK_LOAD  DELAY  ERROR_1000  ERROR_1001  \
0       1         0                 0      0           0           1   
1       2         0                 0      0           0           0   
2       3         0                 1      1           0           0   
3       4         0                 1      0           1           1   
4       5         1                 1      0           1           0   
..    ...       ...               ...    ...         ...         ...   
995   996         0                 0      0           0           0   
996   997         0                 0      0           1           0   
997   998         1                 1      1           0           0   
998   999         0                 1      1           1           1   
999  1000         1                 0      0           0           1   

     ERROR_1002  ERROR_1003      ROOT_CAUSE  
0             0           1     MEMORY_LEAK  
1             0           1     MEMORY_LEAK  
2             1           1     MEMORY_LEAK  
3             0           1     MEMORY_LEAK  
4             1           0   NETWORK_DELAY  
..          ...         ...             ...  
995           0           1  DATABASE_ISSUE  
996           0           0   NETWORK_DELAY  
997           0           0     MEMORY_LEAK  
998           0           0   NETWORK_DELAY  
999           1           0  DATABASE_ISSUE  

[1000 rows x 9 columns]

# Preprocessing for data

# Define and encoding the output 'y'

In [62]:
from sklearn.preprocessing import LabelEncoder

In [63]:
le=LabelEncoder()

In [64]:
y=le.fit_transform(df[['ROOT_CAUSE']])

E:\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [66]:
le.classes_

array(['DATABASE_ISSUE', 'MEMORY_LEAK', 'NETWORK_DELAY'], dtype=object)

# Define  X

In [10]:
X=df.drop(['ID','ROOT_CAUSE'],axis=1)

In [11]:
X

CPU_LOAD  MEMORY_LEAK_LOAD  DELAY  ERROR_1000  ERROR_1001  ERROR_1002  \
0           0                 0      0           0           1           0   
1           0                 0      0           0           0           0   
2           0                 1      1           0           0           1   
3           0                 1      0           1           1           0   
4           1                 1      0           1           0           1   
..        ...               ...    ...         ...         ...         ...   
995         0                 0      0           0           0           0   
996         0                 0      0           1           0           0   
997         1                 1      1           0           0           0   
998         0                 1      1           1           1           0   
999         1                 0      0           0           1           1   

     ERROR_1003  
0             1  
1             1  
2             1  
3             1  
4             0  
..          ...  
995           1  
996           0  
997           0  
998           0  
999           0  

[1000 rows x 7 columns]

In [12]:
y

array([1, 1, 1, 1, 2, 2, 2, 0, 1, 2, 1, 0, 1, 0, 2, 1, 1, 1, 2, 1, 2, 1,
       1, 1, 2, 1, 1, 2, 2, 1, 0, 1, 1, 2, 1, 0, 1, 0, 0, 2, 2, 0, 1, 0,
       2, 2, 2, 0, 2, 0, 1, 0, 0, 0, 2, 1, 2, 1, 0, 0, 2, 1, 0, 1, 2, 1,
       0, 0, 1, 2, 1, 0, 1, 0, 2, 1, 2, 2, 2, 2, 2, 1, 2, 1, 2, 2, 0, 1,
       1, 0, 1, 1, 1, 1, 1, 2, 0, 1, 1, 1, 1, 1, 2, 0, 1, 2, 2, 0, 0, 1,
       2, 2, 2, 0, 0, 0, 1, 1, 1, 2, 1, 0, 2, 0, 0, 2, 2, 2, 1, 0, 2, 1,
       0, 0, 0, 0, 0, 2, 1, 1, 2, 0, 0, 1, 0, 2, 1, 2, 0, 2, 2, 1, 0, 2,
       0, 0, 0, 2, 2, 1, 2, 2, 2, 0, 2, 2, 1, 0, 1, 1, 0, 1, 2, 1, 1, 0,
       1, 1, 1, 0, 2, 1, 0, 0, 1, 0, 1, 2, 0, 1, 1, 1, 2, 1, 2, 0, 0, 0,
       0, 1, 0, 2, 1, 1, 0, 2, 0, 1, 1, 0, 0, 0, 2, 0, 0, 0, 1, 2, 0, 1,
       0, 0, 2, 1, 2, 2, 0, 1, 0, 2, 2, 2, 0, 0, 2, 2, 2, 1, 1, 1, 2, 0,
       2, 0, 2, 0, 2, 1, 0, 1, 2, 1, 2, 2, 1, 2, 0, 0, 2, 2, 1, 1, 0, 0,
       0, 1, 0, 2, 2, 1, 0, 2, 2, 0, 0, 0, 2, 2, 0, 2, 1, 2, 0, 0, 2, 0,
       2, 2, 2, 0, 0, 0, 0, 1, 1, 0, 2, 1, 2, 0, 1,

# Data splitting

In [14]:
from sklearn.model_selection import train_test_split

In [91]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.33, random_state=42)

In [16]:
X_train.shape

(670, 7)

In [68]:
y_train.shape

(670,)

# Build machine Learning Model(SVM)

In [19]:
from sklearn.svm import SVC

In [20]:
svc=SVC()

In [21]:
svc.fit(X_train,y_train)

SVC()

# Prediction of X_test

In [22]:
y_predict=svc.predict(X_test)

# Evaluation of SVM

In [24]:
from sklearn.metrics import confusion_matrix ,accuracy_score,classification_report

In [25]:
print(accuracy_score(y_test,y_predict))

0.8484848484848485


In [26]:
print(confusion_matrix(y_test,y_predict))

[[ 92  14   3]
 [ 14  85   9]
 [  7   3 103]]


In [27]:
print(classification_report(y_test,y_predict))

              precision    recall  f1-score   support

           0       0.81      0.84      0.83       109
           1       0.83      0.79      0.81       108
           2       0.90      0.91      0.90       113

    accuracy                           0.85       330
   macro avg       0.85      0.85      0.85       330
weighted avg       0.85      0.85      0.85       330



# Building Ann Model

In [35]:
#pip install tensorflow

In [96]:
import tensorflow.keras

In [97]:
from keras.models import Sequential
from keras.layers import Dense

In [98]:
ann=Sequential()

#hidden layer
ann.add(Dense(32,input_shape=(7,),activation='relu'))
ann.add(Dense(32,activation='relu'))

#Output layer
ann.add(Dense(3,activation='softmax'))



In [99]:
ann.compile(loss='categorical_crossentropy' ,metrics=['accuracy'])


In [88]:
ann.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_4 (Dense)             (None, 32)                256       
                                                                 
 dense_5 (Dense)             (None, 32)                1056      
                                                                 
 dense_6 (Dense)             (None, 3)                 99        
                                                                 
Total params: 1411 (5.51 KB)
Trainable params: 1411 (5.51 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


# Train the model


Check the shape

In [77]:
X_train.shape

(670, 7)

In [78]:
y_train.shape

(670, 3)

In [79]:
y_train.ndim

2

In [ ]:
#change the output shape  from 1 dimension to 3 it is like get dummies

In [92]:
from keras.utils import to_categorical

In [93]:
y_train=to_categorical(y_train)

In [94]:
y_train.shape

(670, 3)

In [95]:
y_train.ndim

2

Start Training

In [100]:
import tensorflow as tf

In [101]:
ann.fit(X_train,y_train,epochs=20,batch_size=64,verbose=1)


Epoch 1/20
11/11 [==============================] - 1s 5ms/step - loss: 0.9842 - accuracy: 0.6612
Epoch 2/20
11/11 [==============================] - 0s 7ms/step - loss: 0.8839 - accuracy: 0.7612
Epoch 3/20
11/11 [==============================] - 0s 7ms/step - loss: 0.8051 - accuracy: 0.7821
Epoch 4/20
11/11 [==============================] - 0s 5ms/step - loss: 0.7322 - accuracy: 0.7955
Epoch 5/20
11/11 [==============================] - 0s 5ms/step - loss: 0.6710 - accuracy: 0.8075
Epoch 6/20
11/11 [==============================] - 0s 4ms/step - loss: 0.6178 - accuracy: 0.8015
Epoch 7/20
11/11 [==============================] - 0s 7ms/step - loss: 0.5753 - accuracy: 0.8149
Epoch 8/20
11/11 [==============================] - 0s 5ms/step - loss: 0.5430 - accuracy: 0.8254
Epoch 9/20
11/11 [==============================] - 0s 5ms/step - loss: 0.5198 - accuracy: 0.8090
Epoch 10/20
11/11 [==============================] - 0s 4ms/step - loss: 0.5023 - accuracy: 0.8134
Epoch 11/20
11/11 [

# Model Evaluation

In [105]:
ann.evaluate(X_test,y_test)

11/11 [==============================] - 1s 5ms/step - loss: 0.4281 - accuracy: 0.8364


[0.4280778467655182, 0.8363636136054993]

In [102]:
from keras.utils import to_categorical

In [103]:
y_test=to_categorical(y_test)

In [104]:
y_test.shape

(330, 3)